# fly.toml app configuration file generated for whytorch on 2025-09-20T22:57:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whytorch'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.tls]]
  domains = ["whytorch.org", "www.whytorch.org", "docs.whytorch.org"]